postgres:
  username: postgres
  password: postgres
  database: backvotos
  url: localhost:5432

rabbitmq:
  url: localhost
  port: 5672
  username: guest
  password: guest

server:
  port: 8080
  undertow:
    threads:
      worker: 10
      io: 2

spring:
  datasource:
    hikari:
      maximum-pool-size: 5
      minimum-idle: 3