version: "3.9"

networks:
  backvotos-network:
    driver: bridge

services:
  backvotos-postgres:
    image: postgres:14.1
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=backvotos
    ports:
      - "5432:5432"
    volumes:
      - /home/postgresql/data:/var/lib/postgresql/data
    networks:
      - backvotos-network

  backvotos-app:
    build: ./
    environment:
      DB_HOST: backvotos-postgres
      QUEUE_HOST: backvotos-rabbitmq
    ports:
      - "8080:8080"
    networks:
      - backvotos-network
    depends_on:
      - backvotos-postgres
      - backvotos-rabbitmq

  backvotos-rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'backvotos-rabbitmq'
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - /home/rabbitmq/data/:/var/lib/rabbitmq/
    networks:
      - backvotos-network