version: "3.9"

networks:
  backvotos-network:
    driver: bridge

services:
  backvotos-postgres:
    image: postgres:14.1
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=backvotos
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgresql/data:/var/lib/postgresql/data
    networks:
      - backvotos-network

  backvotos-app:
    build: .
    environment:
      DB_HOST: backvotos-postgres
    volumes:
      - ./:/app
    working_dir: /app
    command:  ["/wait-for-it.sh", "localhost:5432", "-t", "5", "--", "./gradlew", "bootRun"]
    ports:
      - "8080:8080"
    networks:
      - backvotos-network
    depends_on:
      - backvotos-postgres
      - backvotos-rabbitmq

  backvotos-rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'backvotos-rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./docker/rabbitmq/data/:/var/lib/rabbitmq/
      - ./docker/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - backvotos-network